# Generated by Django 4.2.11 on 2024-04-10 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kltn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khoaluan',
            name='sinhvien',
            field=models.ManyToManyField(limit_choices_to={'chucvu': 'hocsinh'}, related_name='sinhviens', to=settings.AUTH_USER_MODEL),
        ),
    ]
