# Generated by Django 4.2.11 on 2024-04-11 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kltn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thanhvien_hoidong',
            name='chucvu',
        ),
        migrations.AddField(
            model_name='thanhvien_hoidong',
            name='vaitro',
            field=models.CharField(choices=[('CHU TICH', 'chu tich'), ('THU KY', 'thu ky'), ('PHAN BIEN', 'phan bien'), ('THANH VIEN KHAC', 'thanh vien khac')], default='THANH VIEN KHAC', max_length=100),
        ),
        migrations.AlterField(
            model_name='hoidong',
            name='thanhviens',
            field=models.ManyToManyField(related_name='thanhviens', through='kltn.ThanhVien_HoiDong', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='khoaluan',
            name='gv_huongdan',
            field=models.ManyToManyField(limit_choices_to={'chucvu': 'giangvien'}, related_name='gv_huongdans', to=settings.AUTH_USER_MODEL),
        ),
    ]
