# Generated by Django 4.2.11 on 2024-04-10 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kltn', '0002_khoaluan_sinhvien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diem',
            name='nguoi_danhgia',
        ),
        migrations.AddField(
            model_name='diem_tieuchi',
            name='nguoi_danhgia',
            field=models.ForeignKey(limit_choices_to={'chucvu': 'giangvien'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='diem_tieuchi',
            unique_together={('nguoi_danhgia', 'tieuchi')},
        ),
    ]
