# Generated by Django 4.2.11 on 2024-04-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kltn', '0002_remove_thanhvien_hoidong_chucvu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoidong',
            name='trangthai',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='khoaluan',
            name='trangthai',
            field=models.BooleanField(default=1),
        ),
    ]
