# Generated by Django 4.2.11 on 2024-04-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kltn', '0003_hoidong_trangthai_khoaluan_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoidong',
            name='trangthai',
            field=models.BooleanField(choices=[(1, 'True'), (0, 'False')], default=0),
        ),
    ]
