# Generated by Django 4.2.11 on 2024-04-10 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kltn', '0003_remove_diem_nguoi_danhgia_diem_tieuchi_nguoi_danhgia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoidong',
            name='thanhviens',
            field=models.ManyToManyField(related_name='dsthanhvien', through='kltn.ThanhVien_HoiDong', to=settings.AUTH_USER_MODEL),
        ),
    ]
