# Generated by Django 4.2.11 on 2024-04-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kltn', '0004_alter_hoidong_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoidong',
            name='trangthai',
            field=models.BooleanField(default=False),
        ),
    ]
