# Generated by Django 4.2.11 on 2024-04-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kltn', '0005_alter_hoidong_trangthai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoidong',
            name='trangthai',
        ),
    ]
